### ISSUE TITLE
When are you going to release your prime-arquillian project?

### ISSUE THREAD

**Issue by alex-dukhno** [rmpestano/prime-arquillian#1]
Hi,
One of my project uses JSF PrimeFaces 5.0 framework and I really want to test it with arquillian, but I can't. When I found your project I got hope to test it in future. So I have a little question, When are you going to release your prime-arquillian project? I definitely want to be a beta-tester of your prime-arquillian project. And if I can provide some help for your project I will help with pleasure.

Alex

**Comment by rmpestano** [comment]
Hi Alex,

sorry to disapoint you but i have no roadmap neither time to work on this project now although i can accept and merge pull requests as possible. The first thing to do is to migrate showcase to the new one.

Also remember that the main objective of this project is to provide page object and fragments based on primefaces components to help with your functional tests but the setup(arquillian dependencies and infrastructure) and the test itself is up to you.
